version: '3'
services:
  app1-backend:
    build: .
    environment:
      - NODE_USERNAME = ${NODE_USER}
      - NODE_PASSWORD = ${NODE_PASS}
      - APP_NAME=BackupendApp1
    ports:
      - "3001:3000"

  app2-backend:
    build: .
    environment:
      - NODE_USERNAME = ${NODE_USER}
      - NODE_PASSWORD = ${NODE_PASS}
      - APP_NAME=BackupendApp2
    ports:
      - "3002:3000"

  app3-backend:
    build: .
    environment:
      - NODE_USERNAME = ${NODE_USER}
      - NODE_PASSWORD = ${NODE_PASS}
      - APP_NAME=BackendApp3
    ports:
      - "3003:3000"

