version: '3'
services:
  app1-frontend:
    image: nginx:1.19.0
    build: .
    environment:
      - NGINX_USERNAME = ${NGINX_USER}
      - NGINX_PASSWORD = ${NGINX_PASS}
      - APP_NAME=FrontendApp
    volumes:
      - ./nginx.conf:/opt/homebrew/etc/nginx/nginx.conf
    ports:
      - "3001:3000"
    depends_on:
      - app2-backend
      - app3-backend 

  app2-backend:
    build: .
    environment:
      - NODE_USERNAME = ${NODE_USER}
      - NODE_PASSWORD = ${NODE_PASS}
      - APP_NAME=BackupendApp2
    ports:
      - "3002:3000"

  app3-backend:
    build: .
    environment:
      - NODE_USERNAME = ${NODE_USER}
      - NODE_PASSWORD = ${NODE_PASS}
      - APP_NAME=BackendApp3
    ports:
      - "3003:3000"

